### ISSUE TITLE
Scanner fails to parse certain character-related information

### ISSUE THREAD

**Issue by TheLonelyDevil9** [kel-z/HSR-Scanner#80] opened 2024-03-28 13:52 UTC
I've tried this a few times on the old release as well as the current 1.0.0 release. Basically the scanner fails to parse specific talent/skill/basic/ult levels. The latest scanner output showed this:

[19:18:25] [ERROR] > Dan Heng: Failed to parse 'basic' level. Got '247' instead. Setting to 1.
[19:18:25] [ERROR] > TrailblazerPreservation: Failed to parse 'basic' level. Got '47' instead. Setting to 1.
[19:18:25] [ERROR] > Asta: Failed to parse 'basic' level. Setting to 1.
[19:18:25] [ERROR] > Serval: Failed to parse 'skill' level. Got '1' instead. Setting to 1.
[19:18:25] [ERROR] > Tingyun: Failed to parse 'basic' level. Setting to 1.
[19:18:25] [ERROR] > Qingque: Failed to parse 'skill' level. Got '9542' instead. Setting to 1.
[19:18:25] [ERROR] > Dan Heng: Failed to parse 'skill' level. Got '2' instead. Setting to 1.
[19:18:26] [ERROR] > Herta: Failed to parse 'basic' level. Setting to 1.
[19:18:26] [ERROR] > Asta: Failed to parse 'skill' level. Got '997' instead. Setting to 1.
[19:18:26] [ERROR] > Tingyun: Failed to parse 'skill' level. Got '997' instead. Setting to 1.
[19:18:26] [ERROR] > Qingque: Failed to parse 'ult' level. Got '121' instead. Setting to 1.
[19:18:26] [ERROR] > TrailblazerPreservation: Failed to parse 'skill' level. Setting to 1.
[19:18:26] [ERROR] > Herta: Failed to parse 'skill' level. Got '472' instead. Setting to 1.
[19:18:26] [ERROR] > Tingyun: Failed to parse 'ult' level. Got '1' instead. Setting to 1.
[19:18:26] [ERROR] > Qingque: Failed to parse 'talent' level. Got '1121' instead. Setting to 1.
[19:18:26] [ERROR] > Sushang: Failed to parse 'ult' level. Setting to 1.
[19:18:27] [ERROR] > Herta: Failed to parse 'ult' level. Got '21' instead. Setting to 1.
[19:18:27] [ERROR] > TrailblazerPreservation: Failed to parse 'ult' level. Got '2' instead. Setting to 1.
[19:18:27] [ERROR] > Herta: Failed to parse 'talent' level. Got '1171' instead. Setting to 1.
[19:18:27] [ERROR] > Tingyun: Failed to parse 'talent' level. Setting to 1.
[19:18:27] [ERROR] > Asta: Failed to parse 'talent' level. Setting to 1.
[19:18:27] [ERROR] > Sushang: Failed to parse 'talent' level. Setting to 1.
[19:18:27] [ERROR] > March 7th: Failed to parse 'basic' level. Got '1' instead. Setting to 1.
[19:18:27] [ERROR] > Dan Heng: Failed to parse 'talent' level. Got '75' instead. Setting to 1.
[19:18:27] [ERROR] > Natasha: Failed to parse 'basic' level. Setting to 1.
[19:18:27] [ERROR] > Guinaifen: Failed to parse 'basic' level. Setting to 1.
[19:18:27] [ERROR] > Arlan: Failed to parse 'basic' level. Setting to 1.
[19:18:27] [ERROR] > Hanya: Failed to parse 'basic' level. Setting to 1.
[19:18:27] [ERROR] > TrailblazerPreservation: Failed to parse 'talent' level. Setting to 1.
[19:18:27] [ERROR] > Sampo: Failed to parse 'basic' level. Setting to 1.
[19:18:28] [ERROR] > Natasha: Failed to parse 'skill' level. Got '385' instead. Setting to 1.
[19:18:28] [ERROR] > Lynx: Failed to parse 'skill' level. Setting to 1.
[19:18:28] [ERROR] > Sampo: Failed to parse 'skill' level. Got '193' instead. Setting to 1.
[19:18:28] [ERROR] > March 7th: Failed to parse 'skill' level. Setting to 1.
[19:18:28] [ERROR] > Guinaifen: Failed to parse 'skill' level. Got '85' instead. Setting to 1.
[19:18:28] [ERROR] > Lynx: Failed to parse 'ult' level. Got '1' instead. Setting to 1.
[19:18:28] [ERROR] > Arlan: Failed to parse 'skill' level. Setting to 1.
[19:18:28] [ERROR] > Hanya: Failed to parse 'skill' level. Setting to 1.
[19:18:28] [ERROR] > March 7th: Failed to parse 'ult' level. Setting to 1.
[19:18:28] [ERROR] > Sampo: Failed to parse 'ult' level. Setting to 1.
[19:18:28] [ERROR] > Lynx: Failed to parse 'talent' level. Setting to 1.
[19:18:28] [ERROR] > Arlan: Failed to parse 'ult' level. Setting to 1.
[19:18:28] [ERROR] > Guinaifen: Failed to parse 'ult' level. Setting to 1.
[19:18:28] [ERROR] > Hanya: Failed to parse 'ult' level. Setting to 1.
[19:18:28] [ERROR] > Sampo: Failed to parse 'talent' level. Setting to 1.
[19:18:28] [ERROR] > March 7th: Failed to parse 'talent' level. Setting to 1.
[19:18:29] [ERROR] > Arlan: Failed to parse 'talent' level. Setting to 1.
[19:18:29] [ERROR] > Guinaifen: Failed to parse 'talent' level. Setting to 1.
[19:18:29] [ERROR] > Hanya: Failed to parse 'talent' level. Setting to 1.

**Comment by kel-z** [comment] 2024-03-28 16:54
I see what the issue is now. Is the colour space on your monitor set to sRGB?

**Comment by kel-z** [comment] 2024-03-28 19:35
Nevermind, that matches the settings on my end as well. Something is causing the blue colour of the talent levels to be EVER SO SLIGHTLY brighter than normal, but it's enough to throw off the preprocessing that I apply to the image before OCR.

Yours:
![317792503-9f798ab8-4764-42fd-91c9-97c5a39a8eec](https://github.com/kel-z/HSR-Scanner/assets/24833484/4f45d59e-b90a-4dca-8200-8d8be2e1fa50)
![capture_test_processed](https://github.com/kel-z/HSR-Scanner/assets/24833484/72e86dc2-4867-4267-882d-e13b810e9df4)

Mines:
![093832024291](https://github.com/kel-z/HSR-Scanner/assets/24833484/9158683e-1543-4465-9a71-44e82c67ce31)
![capture_test2_processed](https://github.com/kel-z/HSR-Scanner/assets/24833484/aaa86e30-10ff-4750-af0b-e11b431df979)

The fix should be relatively simple though if I just account for this more "cyan" colour in the image preprocessing function.

**Comment by kel-z** [comment] 2024-03-29 03:41
Maybe, might be worth testing to see if turning that off will fix it.

**Comment by kel-z** [comment] 2024-04-07 04:10
> Nevermind, that matches the settings on my end as well. Something is causing the blue colour of the talent levels to be EVER SO SLIGHTLY brighter than normal, but it's enough to throw off the preprocessing that I apply to the image before OCR.
> 
> Yours:
> ![317792503-9f798ab8-4764-42fd-91c9-97c5a39a8eec](https://github.com/kel-z/HSR-Scanner/assets/24833484/4f45d59e-b90a-4dca-8200-8d8be2e1fa50)
> ![capture_test_processed](https://github.com/kel-z/HSR-Scanner/assets/24833484/72e86dc2-4867-4267-882d-e13b810e9df4)
> 
> Mines:
> ![093832024291](https://github.com/kel-z/HSR-Scanner/assets/24833484/9158683e-1543-4465-9a71-44e82c67ce31)
> ![capture_test2_processed](https://github.com/kel-z/HSR-Scanner/assets/24833484/aaa86e30-10ff-4750-af0b-e11b431df979)
> 
> The fix should be relatively simple though if I just account for this more "cyan" colour in the image preprocessing function.

Yeah it's due to some post processing that your computer is doing like I mentioned here. I don't exactly know what software or hardware you have that is causing it, but I'm guessing that that's the root of the issue.

**Comment by kel-z** [comment] 2024-04-24 05:06
I'll probably create a new release soon now that I have more free time. Hopefully it will fix this issue

**Comment by kel-z** [comment] 2024-04-26 00:40
Could you try testing the character scan again using this pre-release version?

https://github.com/kel-z/HSR-Scanner/releases/tag/v1.1.0-pre.1

**Comment by kel-z** [comment] 2024-05-26 14:54
Sorry, just got back from vacation. Could you turn on debug mode again and send the trace level screenshots for the characters that still fail?

**Comment by kel-z** [comment] 2024-06-04 07:38
Might be resolved in latest release (v1.1.0)

**Closed as completed** 2024-06-20 03:02 UTC
